### ISSUE TITLE
Please consider breaking your theme into an independent repository

### ISSUE THREAD

**Issue by unixorn** [kauefontes/quewui-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the theme is embedded inside a copy of the oh-my-zsh repository.

Please consider breaking it out into its own repository. [Writing Plugins](https://github.com/unixorn/awesome-zsh-plugins/blob/master/Writing_Plugins.md) may be helpful, also look at how [antsy](https://github.com/jeffmhubbard/antsy-zsh-theme) and [powerline](https://github.com/brucehsu/oh-my-zsh-powerline-theme) are packaged.

Thanks!

**Comment by kauefontes** [comment]
Hey @unixorn , I just made it as you recommended. You can check it out in [here](https://github.com/kauefontes/oh-my-quewui).

For any aditional modification, fell free to reach me out!

Thanks!

**Comment by unixorn** [comment]
All it needs now is a license file and it is good to go, thanks!

https://github.com/kauefontes/oh-my-quewui/issues/1

**Comment by unixorn** [comment]
Thanks, adding it
